---
title: "Practica Conglomerados"
author: "Jhonatan Smith Garcia"
date: "28/8/2021"
output: html_document
---
# Taller 4B:

Ejercicio 9.4

datos:

```{r}
N=32
n = 4
Mi = c(25,10,18,16)
mi = c(13,5,9,8)
losqueno = c(3,1,4,2)
pi = losqueno/mi

```

```{r}
EstRazProp <- function(Mi, M0, N, n, mi, pi){
  #Mi Tamaños de los conglomerados
  #N Número total de conglomerados
  #n Número de conglomerados en la muestra
  #mi Tamaño de muestra en el i-ésimo conglomerado
  Mbar <- M0/N
  p_r2 <- sum(Mi*pi)/sum(Mi)
  s2_rupm <- sum(Mi^2*(pi-p_r2)^2/(n-1))
  varp_r2 <- ((N-n)/N)*(1/Mbar^2)*(s2_rupm/n)+(1/(n*N*Mbar^2))*sum(Mi^2*((Mi-mi)/Mi)*(pi*(1-pi)/(mi-1)))
  A_r2 <- M0*p_r2
  varA_r2 <- M0^2*varp_r2
  LEE <- c(2*sqrt(varp_r2), 2*sqrt(varA_r2)) 
  intervalo <- data.frame(LI = c(p_r2 - LEE[1], A_r2 - LEE[2]), LS = c(p_r2 + LEE[1], A_r2 + LEE[2]))
  rownames(intervalo) <- c("P_r2", "A_r2")
  list(Estimaciones = data.frame(P_r2 = p_r2, A_r2 = A_r2), 
       Varianzas = data.frame(varP_r2 = varp_r2, varA_r2 = varA_r2), 
       LEEs = data.frame(LEEP_r2 = LEE[1], LEEA = LEE[2]), 
       Intervalo = intervalo, S2_rUPM = s2_rupm)
  
}

```


```{r}
M0=mean(Mi)*N 
M0
EstRazProp(Mi, M0, N, n, mi, pi)
```

0.2865106 es la proporcion pedida

# Ejercicio 9.5

```{r}
M0 = 450
EstRazProp(Mi, M0, N, n, mi, pi)
```
0.2865106 es la proporcion pedida

# Ejercicio 9.6

Piden total por muestro biestapico

```{r}
N=12
Mi = c(21,23,20,20)
mi = c(10,10,10,10)
mui = c(15.5,15.8,17,14.9) # Medias de cd conglomerado
s_i = c(2.8,3.1,3.5,3.4)

```

calculo de totales:

```{r}
ti = Mi*mui
ti
varianza = var(ti)
varianza
```
```{r}
upm = mean(ti)
upm
```
```{r}
mu_2cong = (1/4)*sum(Mi*mui)
mu_2cong
```
```{r}
12*upm # resultado total llamadas
```

```{r}
var_t2 = N^2*(1-n/N)*(varianza/4)+(N/4)*sum((1-10/Mi)*(s_i)/10)
var_t2
```
```{r}
B = 2*sqrt(var_t2)
B
```
Melo


# Ejercicio 9.7

Datos

```{r}
N = 7
n = 3
Mi = c(46,67,93)
mi = c(9,13,20)
pi = c(1/9,2/13,1/20)
```

Nuevamente no tenemos M0.

```{r}
M0=mean(Mi)*N 
EstRazProp(Mi, M0, N, n, mi, pi)
```
0.09742138 es la proporcion de los que estan a favor.

0.07666911 Limite del error 


# Ejercicio 9.8

```{r}
#Datos

N = 10
n =4 
Mi = c(12,15,14,21)
mi = 6
conglomerado =(c(15,14,21,13,9,10),c(4,6,10,9,8,5),c(10,11,14,10,9,15),c(8,3,4,1,2,5))
```

```{r}
si2=c()
for (i in 1:length(conglomerado)) {
  si2[i]=var(conglomerado[[i]])
}
```

```{r}
taui=c()
for (i in 1:length(conglomerado)) {
  taui[i]=sum(conglomerado[[i]])
}
```

```{r}
yibar=c()
for (i in 1:length(conglomerado)) {
  yibar[i]=mean(conglomerado[[i]])
}

```


```{r}
EstRazMu(Mi, M0, N, n, mi, si2,  taui, yibar)
```

```{r}
totales = Mi*yibar
totales
```
```{r}
upm = mean(totales)
upm
```
```{r}
mediamu = sum(totales)/sum(Mi) # Media pedida. No chimbee
mediamu
```

```{r}
var_ump = sum((totales-Mi*mediamu)^2)/(n-1)
var_ump
```
```{r}
Mbar = mean(Mi)
var_mu_r = (1-n/N)*var_ump/(n*Mbar^2)+sum((Mi*(Mi-6))*varianza)/(n*N*6*Mbar^2)

var_mu_r
```

```{r}
B = 2*sqrt(var_mu_r)
B
```






























