---
title: "Laboratorio 1-Arboles"
author: "Jhonatan Smith Garcia"
date: "19/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("ISLR")
install.packages("tree")
install.packages("MASS")
install.packages("randomForest")
install.packages("gbm")

```

```{r}
library(ISLR)
library(tree)

```

La base de datos consiste en un conjunto simulado de ventas de asientos para niño en 400 tiendas distintas.
Acá se creará una variable denominada High, la cual toma el valor de “Yes” si la variable Sales excede el
valor 8 y toma el valor de “No” en cualquier otro caso.


```{r}
#data("Carseats")
#View(Carseats)
attach(Carseats)
High = ifelse(Sales <= 8,"No","Yes")
```

Se crea un único conjunto de datos.

```{r}
Carseats = data.frame(Carseats,High)
#Carseats$High2 = ifelse(Sales <= 8,"No","Yes") # Otra forma
```

Se eliminan columnas repetidas


```{r}
Carseats$High= as.factor(Carseats$High)
```


```{r}
#Carseats = Carseats[,-13] asi hasta borrar las agregadas

tree.carseats = tree(High~.-Sales, data = Carseats)
```


```{r}
library(magrittr)
```

```{r}
tree.carseats %>% summary
```


