---
title: "Get Started"
output: flexdashboard::flex_dashboard
---

```{r setup, include = F, message = F}
if(!require(pacman)){install.packages("pacman"); library(pacman)}
pacman::p_load("tidyverse", "ggplot2", "pBrackets", "knitr", "HH", "car", "rgl","latex2exp", "sampling","biotools","flexdashboard","MASS","mvtnorm","MVN")
source("funcionesR/funciones.R", local = knitr::knit_global())
#source("funcionesR/Functions.R", local = knitr::knit_global())
```

**Graf_Super_Contor 1**
=========================================

Column 1 pag 3
--------------------------------------------------

### Superficie de Probabilidad

```{r, echo=FALSE,results="asis",comment=FALSE,message=FALSE}
mu<-c(0,0)
sigma<-matrix(c(3,2,2,3),ncol=2)
superficie_NB(mu,sigma)
```

$Z=f(x,y\ ;\ \mu_1=`r mu[1]`,\mu_2=`r mu[2]`,\sigma_{11}=`r sigma[1,1]`,\sigma_{22}=`r sigma[2,2]`,\sigma_{12}=`r sigma[1,2]`,\rho=`r round(sigma[1,2]/sqrt(sigma[1,1]*sigma[1,1]),3)`)$

### Contorno de Probabilidad 

```{r, echo=FALSE,results="asis",comment=FALSE,message=FALSE}
#niveles <- pretty(range(z, finite = TRUE), 4)
contorno_NB(mu,sigma)
```

Column 2 pag 3
--------------------------------------------------

### Superficie de Probabilidad

```{r, echo=FALSE,results="asis",comment=FALSE,message=FALSE}
mu<-c(0,0)
sigma<-matrix(c(1,0,0,1),ncol=2)
superficie_NB(mu,sigma)
```

$Z=f(x,y\ ;\ \mu_1=`r mu[1]`,\mu_2=`r mu[2]`,\sigma_{11}=`r sigma[1,1]`,\sigma_{22}=`r sigma[2,2]`,\sigma_{12}=`r sigma[1,2]`,\rho=`r round(sigma[1,2]/sqrt(sigma[1,1]*sigma[1,1]),3)`)$

### Contorno de Probabilidad 

```{r, echo=FALSE,results="asis",comment=FALSE,message=FALSE}
#niveles <- pretty(range(z, finite = TRUE), 4)
contorno_NB(mu,sigma)
```

**Graf_Super_Contor 2**
=========================================

Column 1 pag 3
--------------------------------------------------

### Superficie de Probabilidad

```{r, echo=FALSE,results="asis",comment=FALSE,message=FALSE}
mu<-c(0,0)
sigma<-matrix(c(3,-2,-2,3),ncol=2)
superficie_NB(mu,sigma)
```

$Z=f(x,y\ ;\ \mu_1=`r mu[1]`,\mu_2=`r mu[2]`,\sigma_{11}=`r sigma[1,1]`, \sigma_{22}=`r sigma[2,2]`,\sigma_{12}=`r sigma[1,2]`,\rho=`r round(sigma[1,2]/sqrt(sigma[1,1]*sigma[1,1]),3)`)$

### Contorno de Probabilidad 

```{r, echo=FALSE,results="asis",comment=FALSE,message=FALSE}
#niveles <- pretty(range(z, finite = TRUE), 4)
contorno_NB(mu,sigma)
```

Column 2 pag 3
--------------------------------------------------

### Superficie de Probabilidad

```{r, echo=FALSE,results="asis",comment=FALSE,message=FALSE}
mu<-c(0,0)
sigma<-matrix(c(3,0,0,3),ncol=2)
superficie_NB(mu,sigma)
```

$Z=f(x,y\ ;\ \mu_1=`r mu[1]`,\mu_2=`r mu[2]`,\sigma_{11}=`r sigma[1,1]`,\sigma_{22}=`r sigma[2,2]`,\sigma_{12}=`r sigma[1,2]`,\rho=`r round(sigma[1,2]/sqrt(sigma[1,1]*sigma[1,1]),3)`)$

### Contorno de Probabilidad 

```{r, echo=FALSE,results="asis",comment=FALSE,message=FALSE}
#niveles <- pretty(range(z, finite = TRUE), 4)
contorno_NB(mu,sigma)
```

