---
title: "Get Started"
output: flexdashboard::flex_dashboard
---

```{r setup, include = F, message = F}
if(!require(pacman)){install.packages("pacman"); library(pacman)}
pacman::p_load("tidyverse", "ggplot2", "pBrackets", "knitr", "HH", "car", "rgl","latex2exp", "sampling","biotools","flexdashboard","MASS","mvtnorm","MVN")
source("funcionesR/funciones.R", local = knitr::knit_global())
#source("funcionesR/Functions.R", local = knitr::knit_global())
```

**Disper_Puntos-$\chi^2$**
=========================================

Column 1 pag 1
--------------------------------------------------

### **Generación de Datos Normales Bivariados**

```{r}
mu=c(2,2)
sigma<-matrix(c(5,4,4,5),ncol=2)
set.seed(12345)
datos<-round(mvrnorm(n=100, mu,sigma),3)
xbar1<-apply(datos, 2, mean)
var1<-var(datos)
```
Datos Generados de una Normal Bivariada con parámetros:
$$
\underline{\mu}=\begin{bmatrix} `r mu[1]` \\ `r mu[2]`  \end{bmatrix} \ \ \ \ \ y \ \ \ \ \boldsymbol{\Sigma}=\begin{bmatrix} `r sigma[1,1]` & `r sigma[1,2]` \\ `r sigma[2,1]` & `r sigma[2,2]` \end{bmatrix} $$
Las estimaciones muestrales de los parámetros son:
$$
\underline{\overline{x}}=\begin{bmatrix} \overline{x}_1 \\ \overline{x}_2  \end{bmatrix}=\begin{bmatrix} `r round(xbar1[1],3)` \\ `r round(xbar1[2],3)`  \end{bmatrix} \ \ \ \ \ y \ \ \ \ \boldsymbol{S}=\begin{bmatrix} s_{11} & s_{12} \\ s_{21} & s_{22} \end{bmatrix} =\begin{bmatrix} `r round(var1[1,1],3)` & `r round(var1[1,2],3)` \\ `r round(var1[2,1],3)` & `r round(var1[2,2],3)` \end{bmatrix} 
$$

### **Contorno de Probabilidad**

**Definición:** \ \ Una región de confianza del $(1-\alpha)100\%$ para el vector  $\underline{x}$ de una población normal $2$-dimensional, es el conjunto de todos los valores $\underline{x}$ que satisfacen:
$$
n(\underline{x}-\underline{\overline{\boldsymbol{x}}})^t\boldsymbol{S}^ {-1}(\underline{x}-\underline{\overline{\boldsymbol{x}}}) \leq c^2= \chi^2_{1-\alpha\ ,\ p}
$$
\textcolor{blue}{Para $p=2$ la región es una elipse  centrada en $\underline{\overline{\boldsymbol{x}}}$}
$$
n\begin{bmatrix}
x_1-\overline{x}_1 \\ x_2 -\overline{x}_2
\end{bmatrix}^t \begin{bmatrix}
s_{11} & s_{12} \\ s_{21} & s_{22}
\end{bmatrix}^{-1}  \begin{bmatrix}
x_1 - \overline{x}_1 \\ x_2 - \overline{x}_2
\end{bmatrix}  \leq  c^2=\chi^2_{1-\alpha\ ,\ p}
$$
$$
n\begin{bmatrix}
x_1-`r round(xbar1[1],3)` \\ x_2 -`r round(xbar1[2],3)`
\end{bmatrix}^t \begin{bmatrix}
`r round(var1[1,1],3)` & `r round(var1[1,2],3)` \\ `r round(var1[2,1],3)` & `r round(var1[2,2],3)`
\end{bmatrix}^{-1}  \begin{bmatrix}
x_1 - `r round(xbar1[1],3)` \\ x_2 - `r round(xbar1[2],3)`
\end{bmatrix}  \leq  c^2=\chi^2_{1-\alpha\ ,\ p}
$$
$$
\hspace{-0.5cm} AX_1^2+BX_2^2+CX_1+DX_2+EX_1X_2 +F \leq 0
$$

Column 2 pag 1
--------------------------------------------------

### **Gráfico de Dispersión de Puntos**

```{r}
mu=c(2,2)
sigma<-matrix(c(5,4,4,5),ncol=2)
set.seed(12345)
datos<-round(mvrnorm(n=100, mu,sigma),3)
representa(datos)   
```

### **Contornos de probabilidad del $90\%$ y $95\%$**

```{r}
mu=c(2,2)
sigma<-matrix(c(5,4,4,5),ncol=2)
set.seed(12345)
datos<-round(mvrnorm(n=100, mu,sigma),3)
representa2c_ng(datos,0.9,0.95)   
```

**Disper_Puntos-kF**
=========================================

Column 1 pag 2
--------------------------------------------------

### **Generación de Datos Normales Bivariados**

````{r}
mu=c(2,2)
sigma<-matrix(c(5,4,4,5),ncol=2)
set.seed(12345)
datos<-round(mvrnorm(n=20, mu,sigma),3)
xbar2<-apply(datos, 2, mean)
var2<-var(datos)
````

Datos Generados de una Normal Bivariada con parámetros:
$$
\underline{\mu}=\begin{bmatrix} `r mu[1]` \\ `r mu[2]`  \end{bmatrix} \ \ \ \ \ y \ \ \ \ \boldsymbol{\Sigma}=\begin{bmatrix} `r sigma[1,1]` & `r sigma[1,2]` \\ `r sigma[2,1]` & `r sigma[2,2]` \end{bmatrix} 
$$
Las estimaciones muestrales de los parámetros son:
$$
\underline{\overline{x}}=\begin{bmatrix} \overline{x}_1 \\ \overline{x}_2  \end{bmatrix}=\begin{bmatrix} `r round(xbar2[1],3)` \\ `r round(xbar2[2],3)`  \end{bmatrix} \ \ \ \ \ y \ \ \ \ \boldsymbol{S}=\begin{bmatrix} s_{11} & s_{12} \\ s_{21} & s_{22} \end{bmatrix}=\begin{bmatrix} `r round(var2[1,1],3)` & `r round(var2[1,2],3)` \\ `r round(var2[2,1],3)` & `r round(var2[2,2],3)` \end{bmatrix} 
$$

### **Contorno de Probabilidad**

**Definición:** \ \ Una región de confianza del $(1-\alpha)100\%$ para el vector  $\underline{x}$ de una población normal $2$-dimensional, es el conjunto de todos los valores $\underline{x}$ que satisfacen:
$$
n(\underline{x}-\underline{\overline{\boldsymbol{x}}})^t\boldsymbol{S}^ {-1}(\underline{x}-\underline{\overline{\boldsymbol{x}}}) \leq c^2= \frac{(n-1)p}{(n-p)}F_{\alpha; p,n-p}
$$
\textcolor{blue}{Para $p=2$ la región es una elipse  centrada en $\underline{\overline{\boldsymbol{x}}}$}
$$
n\begin{bmatrix}
x_1-\overline{x}_1 \\ x_2 -\overline{x}_2
\end{bmatrix}^t \begin{bmatrix}
s_{11} & s_{12} \\ s_{21} & s_{22}
\end{bmatrix}^{-1}  \begin{bmatrix}
x_1 - \overline{x}_1 \\ x_2 - \overline{x}_2
\end{bmatrix}  \leq  c^2=\frac{(n-1)p}{(n-p)}F_{1-\alpha\ ;\ p,n-p}
$$
$$
n\begin{bmatrix}
x_1-`r round(xbar2[1],3)` \\ x_2 -`r round(xbar2[2],3)`
\end{bmatrix}^t \begin{bmatrix} `r round(var2[1,1],3)` & `r round(var2[1,2],3)` \\ `r round(var2[2,1],3)` & `r round(var2[2,2],3)` \end{bmatrix}^{-1}  \begin{bmatrix}
x_1 - `r round(xbar2[1],3)` \\ x_2 - `r round(xbar2[2],3)`
\end{bmatrix}  \leq  c^2=\frac{(n-1)p}{(n-p)}F_{1-\alpha\ ;\ p,n-p}
$$
$$
\hspace{-0.5cm} AX_1^2+BX_2^2+CX_1+DX_2+EX_1X_2 +F \leq 0
$$

Column 2 pag 2
--------------------------------------------------

### **Gráfico de Dispersión de Puntos**

```{r}
mu=c(2,2)
sigma<-matrix(c(5,4,4,5),ncol=2)
set.seed(12345)
datos<-round(mvrnorm(n=20, mu,sigma),3)
representa(datos)   
```

### **Contornos de probabilidad del $90\%$ y $95\%$**

```{r}
mu=c(2,2)
sigma<-matrix(c(5,4,4,5),ncol=2)
set.seed(12345)
datos<-round(mvrnorm(n=20, mu,sigma),3)
representa2c_np(datos,0.9,0.95)   
```

