---
title: "Get Started"
output: flexdashboard::flex_dashboard
---

```{r setup, include = F, message = F}
if(!require(pacman)){install.packages("pacman"); library(pacman)}
pacman::p_load("tidyverse", "ggplot2", "pBrackets", "knitr", "HH", "car", "rgl","latex2exp","magrittr","ICSNP","rrcov",
              "Hotelling", "sampling","biotools","flexdashboard","MASS","mvtnorm","MVN")
source("funciones.R", local = knitr::knit_global())
source("Functions.R", local = knitr::knit_global())
```

**PH Contrastes $C\underline{\mu}=\underline{\mu}_0$**
=========================================

Column 1 pag 1
--------------------------------------------------

### **Generación de Datos Normales Bivariados**

```{r}
alfa<-c(0.05)
mu=c(0,0)
sigma<-matrix(c(4,-3,-3,4),ncol=2)
#datos<-round(mvrnorm(n=100, mu,sigma),3)
#datos6<-read.table("G:\\Mi unidad\\1_A_A_CURSOS_UNAL\\1_MULTIVARIADO\\2022_I\\tableros_IAM\\datos\\datos6.txt",header=TRUE)
datos6 <- read.table("datos6.txt",header=TRUE)
datos6$Grupos %<>% as.factor()
grupo1<-datos6 %>% filter(Grupos=="1")
grupo2<-datos6 %>% filter(Grupos=="2")
grupo3<-datos6 %>% filter(Grupos=="3")
xbar<-apply(grupo1[,1:2], 2, mean)
xvar<-var(grupo1[,1:2])

C<-matrix(c(1,0,2,1,1,-1),byrow=T,ncol=3)
mu_0<-c(0,0)
```
Datos Generados de una Normal Bivariada con parámetros:
$$
\underline{\mu}=\begin{bmatrix} `r mu[1]` \\ `r mu[2]`  \end{bmatrix} \ \ \ \ \ y \ \ \ \ \boldsymbol{\Sigma}=\begin{bmatrix} `r sigma[1,1]` & `r sigma[1,2]` \\ `r sigma[2,1]` & `r sigma[2,2]` \end{bmatrix} $$

Las estimaciones muestrales de los parámetros son:
$$
\underline{\overline{x}}=\begin{bmatrix} \overline{x}_1 \\ \overline{x}_2  \end{bmatrix}= \begin{bmatrix} `r  round(xbar[1],3)` \\ `r round(xbar[2],3)`  \end{bmatrix} \ \ \ \ \ y \ \ \ \ \boldsymbol{S}_x=\begin{bmatrix} s_{11} & s_{12} \\ s_{21} & s_{22} \end{bmatrix} =  \begin{bmatrix} `r round(xvar[1,1],3)` & `r round(xvar[1,2],3)` \\ `r round(xvar[2,1],3)` & `r round(xvar[2,2],3)` \end{bmatrix} 
$$
Se desea realizar la siguiente prueba de hipótesis:
$$
\begin{cases}
H_0 \ : \  C \underline{\mu} = \underline{\mu}_0 \\ \\
H_0 \ : \  C \underline{\mu} \neq \underline{\mu}_0 
\end{cases} 
$$
El estadístico de prueba es:
$$
T_0^2= n \bigl(C \underline{\overline{\boldsymbol{x}}} - \underline{\mu}_0\bigr)^t \bigl[C \boldsymbol{S} C^t\bigr]^{-1}\bigl(C \underline{\overline{\boldsymbol{x}}} - \underline{\mu}_0\bigr) \sim cF
$$
$$
\text{con:}\ \ \ c=\frac{(n-1)k}{n-k}
$$
Se rechaza $H_0$  si:\ \  $T_0^2 > cF \ \  \text{ó}\ \ \ F_0=\frac{1}{c}T_0^2>F_{tabla}=F_{1-\alpha\ ; \ k\ ,\ n-k}$.


Column 2 pag 1 
--------------------------------------------------

### **Prueba de Hipótesis: $H_0 \ : \ C\underline{\mu}=\underline{\mu}_0$**

**Se desea probar**: 
$$
H_0 :\ C \underline{\mu} =  \underline{\mu}_0 \Longleftrightarrow C \underline{\mu} = \begin{bmatrix} `r C[1,1]` & `r C[1,2]` & `r C[1,3]` \\ `r C[2,1]` & `r C[2,2]` & `r C[2,3]` \end{bmatrix}\begin{bmatrix}\mu_1 \\ \mu_2 \\ \mu_3 \end{bmatrix} =  \begin{bmatrix} `r mu_0[1]` \\ `r mu_0[2]` \end{bmatrix} \Longleftrightarrow \begin{bmatrix} \mu_1-2\mu_3 \\ \mu_1+\mu_2-\mu_3 \end{bmatrix} = \begin{bmatrix} `r mu_0[1]` \\ `r mu_0[2]` \end{bmatrix} 
$$
$$
H_0\ : \ \mu_1-2\mu_3=`r mu_0[1]`,\ \  \mu_1+\mu_2-\mu_3=`r mu_0[1]` \   \Longleftrightarrow  \ \ \mu_1=2\mu_3,\ \  \mu_1+\mu_2=\mu_3
$$

```{r echo = TRUE}
res_CU<-HT2_CU(grupo1[,1:3],C,mu_0,0.05)
kable(res_CU)
```

**PH Contrastes $C\underline{\mu}=\underline{\mu}_0$\ ; \  $n$-Grande**
=========================================

Column 1 pag 2
--------------------------------------------------

### **Generación de Datos Normales Bivariados**

**Datos Generados de una Normal Bivariada con parámetros**:
$$
\underline{\mu}=\begin{bmatrix} `r mu[1]` \\ `r mu[2]`  \end{bmatrix} \ \ \ \ \ y \ \ \ \ \boldsymbol{\Sigma}=\begin{bmatrix} `r sigma[1,1]` & `r sigma[1,2]` \\ `r sigma[2,1]` & `r sigma[2,2]` \end{bmatrix} $$

**Las estimaciones muestrales de los parámetros son**:
$$
\underline{\overline{x}}=\begin{bmatrix} \overline{x}_1 \\ \overline{x}_2  \end{bmatrix}= \begin{bmatrix} `r  round(xbar[1],3)` \\ `r round(xbar[2],3)`  \end{bmatrix} \ \ \ \ \ y \ \ \ \ \boldsymbol{S}_x=\begin{bmatrix} s_{11} & s_{12} \\ s_{21} & s_{22} \end{bmatrix} =  \begin{bmatrix} `r round(xvar[1,1],3)` & `r round(xvar[1,2],3)` \\ `r round(xvar[2,1],3)` & `r round(xvar[2,2],3)` \end{bmatrix} 
$$
**Se desea realizar la siguiente prueba de hipótesis**:
$$
\begin{cases}
H_0 \ : \  C \underline{\mu} = \underline{\mu}_0 \\ \\
H_0 \ : \  C \underline{\mu} \neq \underline{\mu}_0 
\end{cases} 
$$
**El estadístico de prueba es**:
$\chi_0^2= n \bigl(C \underline{\overline{\boldsymbol{x}}} - \underline{\mu}_0\bigr)^t \bigl[C \boldsymbol{S} C^t\bigr]^{-1}\bigl(C \underline{\overline{\boldsymbol{x}}} - \underline{\mu}_0\bigr) \sim \chi_{k}^2$

**Se rechaza $H_0$\ : \ \  si} $\chi_0^2 >  \chi_{\alpha; k}^2$**.


Column 2 pag 2 
--------------------------------------------------

### **Prueba de Hipótesis: $H_0 \ : \ C\underline{\mu}=\underline{\mu}_0$\ ; \  $n$-Grande**

Se desea probar:  
$$
H_0 :\ C \underline{\mu} =  \underline{\mu}_0 \Longleftrightarrow C \underline{\mu} = \begin{bmatrix}1 & 0 & 2 \\ 1 & 1 & -1 \end{bmatrix}\begin{bmatrix}\mu_1 \\ \mu_2 \\ \mu_3 \end{bmatrix} =  \begin{bmatrix} 0 \\ 0 \end{bmatrix} \Longleftrightarrow \begin{bmatrix} \mu_1-2\mu_3 \\ \mu_1+\mu_2-\mu_3 \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \end{bmatrix} 
$$
$$
H_0\ : \ \mu_1-2\mu_3=0,\ \  \mu_1+\mu_2-\mu_3=0 \   \Longleftrightarrow  \ \ \mu_1=2\mu_3,\ \  \mu_1+\mu_2=\mu_3
$$

```{r echo=TRUE}
res_CUng<-HT2_CU_ngrande(grupo1[,1:3],C,mu_0,0.05)
kable(res_CUng)
```

