---
title: "Final_IC"
author: "Valentina Tamayo"
date: "18/1/2022"
output: html_document
---
**INTERVALOS DE CONFIANZA para medias** 

```{r}
variable <- as.numeric(readline (prompt = "1. Si la muestra proviene de una normal\n2. Si la muestra es una no normal mayor a 30 \n"))
if (variable==1){
  tipo <- readline (prompt ="1. Si conoce la desviación\n2. Si es desconocida la desviacion\n")
  if(tipo==1){
    promedio<- as.numeric(readline(prompt ="Ingrese la media: "))
    n<-as.numeric(readline(prompt ="Ingrese el tamaño de la muestra: "))
    desv<- as.numeric(readline(prompt ="Ingrese la desviacion estandar: "))
    conf<- as.numeric(readline(prompt ="Ingrese el nivel de confianza en decimal: "))
    x<-(1-conf)/2
    
    
    q<-qnorm(x,mean=0,sd=1,lower.tail=FALSE)
    
    
    L<- round(promedio-q*(desv/sqrt(n)),4)
    
    U<- round(promedio+q*(desv/sqrt(n)),4)
    
    cat("El intervalo de confianza es: ","(",L,",",U,")")}
  
    else if(tipo==2){
      promedio<- as.numeric(readline(prompt ="Ingrese la media: "))
      n<- as.numeric(readline(prompt ="Ingrese el tamaño de la muestra: "))
      desv<- as.numeric(readline(prompt ="Ingrese la desviacion muestral: "))
      conf<- as.numeric(readline(prompt ="Ingrese el nivel de confianza en decimal: "))
      x<-(1-conf)/2
      
      q<-qt(x,n-1,lower.tail=FALSE)
      

      L<- round(promedio-q*(desv/sqrt(n)),4)

      U<- round(promedio+q*(desv/sqrt(n)),4)

      cat("El intervalo de confianza es: ","(",L,",",U,")")
    }
    
}

if(variable==2){
    promedio<- as.numeric(readline(prompt ="Ingrese la media: "))
    n<-as.numeric(readline(prompt ="Ingrese el tamaño de la muestra: "))
    desv<- as.numeric(readline(prompt ="Ingrese la desviacion estandar o desviación muestral: "))
    conf<- as.numeric(readline(prompt ="Ingrese el nivel de confianza en decimal: "))
    x<-(1-conf)/2
    
    
    q<-qnorm(x,mean=0,sd=1,lower.tail=FALSE)
    
    
    L<- round(promedio-q*(desv/sqrt(n)),4)
    
    U<- round(promedio+q*(desv/sqrt(n)),4)
    
    cat("El intervalo de confianza es: ","(",L,",",U,")")
}
```

**IC para diferencia de medias**

```{r}
variable <- as.numeric(readline (prompt = "1. Si la muestra proviene de una normal\n2. Si la muestra es una no normal mayor a 30 "))
tipo <- as.numeric(readline (prompt ="1. Si conoce la desviación\n2. si es desconocida la desviacion\n"))

if (variable==1 & tipo==1){
  media_x<-as.numeric(readline(prompt ="Ingrese la media de x: "))
  media_y<-as.numeric(readline(prompt ="Ingrese la media de y: "))
  s_x<- as.numeric(readline(prompt ="Ingrese la desviacion estandar o desviación muestral de x: "))
  s_y=as.numeric(readline(prompt ="Ingrese la desviacion estandar o desviación muestral de y: "))
  n<-as.numeric(readline(prompt ="Ingrese el tamaño de la muestra de x: "))
  m<-as.numeric(readline(prompt ="Ingrese el tamaño de la muestra de y: "))
  
  conf<- as.numeric(readline(prompt ="Ingrese el nivel de confianza en decimal: "))
  alfa_2<-(1-conf)/2
  
  
  z_alfa<-qnorm(alfa_2,lower.tail = FALSE)
  
  L<-(media_x-media_y)-(z_alfa*sqrt(s_x^2/n+s_y^2/m))
  U<-(media_x-media_y)+(z_alfa*sqrt(s_x^2/n+s_y^2/m))
  cat("El intervalo de confianza es: ","(",L,",",U,")")
  
  
}

if(variable==1 & tipo==2){
  comparar <- as.numeric(readline (prompt = "1. Si las desviaciones son iguales\n2. Si las desviaciones son diferentes: "))
  
  if(comparar==1){
  media_x<-as.numeric(readline(prompt ="Ingrese la media de x: "))
  media_y<-as.numeric(readline(prompt ="Ingrese la media de y: "))
  s_x<- as.numeric(readline(prompt ="Ingrese la desviacion estandar o desviación muestral de x: "))
  s_y=as.numeric(readline(prompt ="Ingrese la desviacion estandar o desviación muestral de y: "))
  n<-as.numeric(readline(prompt ="Ingrese el tamaño de la muestra de x: "))
  m<-as.numeric(readline(prompt ="Ingrese el tamaño de la muestra de y: "))
  
  conf<- as.numeric(readline(prompt ="Ingrese el nivel de confianza en decimal: "))
  alfa_2<-(1-conf)/2
  
  sp<-sqrt(((n-1)*s_x^2+(m-1)*s_y^2)/(n+m-2))
  
  t_alfa<-qt(alfa_2,df=n+m-2,lower.tail = FALSE)
  
  L<-(media_x-media_y)-(t_alfa*sp*sqrt(1/n+1/m))
  U<-(media_x-media_y)+(t_alfa*sp*sqrt(1/n+1/m))
  cat("El intervalo de confianza es: ","(",L,",",U,")")
  }
  
  if(comparar==2){
    media_x<-as.numeric(readline(prompt ="Ingrese la media de x: "))
    media_y<-as.numeric(readline(prompt ="Ingrese la media de y: "))
    desv_x<- as.numeric(readline(prompt ="Ingrese la desviacion estandar o desviación muestral de x: "))
    desv_y=as.numeric(readline(prompt ="Ingrese la desviacion estandar o desviación muestral de y: "))
    n<-as.numeric(readline(prompt ="Ingrese el tamaño de la muestra de x: "))
    m<-as.numeric(readline(prompt ="Ingrese el tamaño de la muestra de y: "))
    
    conf<- as.numeric(readline(prompt ="Ingrese el nivel de confianza en decimal: "))
    alfa_2<-(1-conf)/2
    
    v<-((desv_x^2/n+desv_y^2/m)^2)/((((desv_x^2/n)^2)/(n-1))+  (((desv_y^2/m)^2)/(m-1)))
    
    t_alfa<-qt(alfa_2,df=v,lower.tail = FALSE)
  
    L<-((media_x-media_y)-t_alfa*sqrt(desv_x^2/n+desv_y^2/m))
    
    U<-((media_x-media_y)+t_alfa*sqrt(desv_x^2/n+desv_y^2/m))
    
    print(c(L,U))
      
  }
}

if(variable==2){
  media_x<-as.numeric(readline(prompt ="Ingrese la media de x: "))
  media_y<-as.numeric(readline(prompt ="Ingrese la media de y: "))
  s_x<- as.numeric(readline(prompt ="Ingrese la desviacion estandar o desviación muestral de x: "))
  s_y=as.numeric(readline(prompt ="Ingrese la desviacion estandar o desviación muestral de y: "))
  n<-as.numeric(readline(prompt ="Ingrese el tamaño de la muestra de x: "))
  m<-as.numeric(readline(prompt ="Ingrese el tamaño de la muestra de y: "))

  conf<- as.numeric(readline(prompt ="Ingrese el nivel de confianza en decimal: "))
  alfa_2<-(1-conf)/2
  
  
  z_alfa<-qnorm(alfa_2,lower.tail = FALSE)
  z_alfa
  
  L<-(media_x-media_y)-(z_alfa*sqrt(s_x^2/n+s_y^2/m))
  U<-(media_x-media_y)+(z_alfa*sqrt(s_x^2/n+s_y^2/m))
  cat("El intervalo de confianza es: ","(",L,",",U,")")
}
```






