---
title: | 
  <center> Actividad # 2 </center>
  <center> IAM </center>
author: |
  <center> Jhonatan Smith Garcia</center>
  <center> c.c 1039705595</center>
date: "Abril 29, 2022"
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Ejercicio 1.

Sea X una $N_{3}(\mu, \Sigma) \operatorname{con} \mu^{T}=[-3,1,4]$ y sea:

$$ \Sigma=\left[\begin{array}{ccc}
1 & -2 & 0 \\
-2 & 5 & 0 \\
0 & 0 & 2
\end{array}\right]$$


**a**

$$\underline{\boldsymbol{x}}=\left[\begin{array}{c}
\underline{\boldsymbol{x}}^{(1)} \\
\cdots \\
\underline{\boldsymbol{x}}^{(2)}
\end{array}\right] \sim N_{p}\left[\left(\begin{array}{c}
\underline{\mu}^{(1)} \\
\cdots \\
\underline{\mu}^{(2)}
\end{array}\right),\left(\begin{array}{ccc}
\boldsymbol{\Sigma}_{11} & \mid & \boldsymbol{\Sigma}_{12} \\
-- & -- & -- \\
\boldsymbol{\Sigma}_{21} & \mid & \boldsymbol{\Sigma}_{22}
\end{array}\right)\right]$$

Si se tiene la anterior particio  de vectores, tenga presente qu epor Hipotesis, el vector original X era un vector p variado. Esto implica que cualquier particion de dicho vector es normal.

Ahora, basta mirar la matriz de var-cov para mirar independencia y en este caso:

$$\underline{\boldsymbol{x}}^{(1)} \perp \underline{\boldsymbol{x}}^{(2)} \quad \text { Sii } \quad \boldsymbol{\Sigma}_{12}=\boldsymbol{\Sigma}_{21}^{t}=O$$
Ahora, con esto en mente; dadas las isguientes particiones, de determinará la independencia de los vectores.


$\text { Se tiene que } \underline{X}^{(1)}=X_{1}, y \underline{X}^{(2)}=X_{2} \text {, asi que: }$ entonces:

$$\underline{\mathbf{X}}=\left[\begin{array}{c}
\underline{X}^{(1)} \\
\ldots \\
\underline{X}^{(2)}
\end{array}\right] \sim N_{2}\left[\left[\begin{array}{c}
-3 \\
\ldots \\
1
\end{array}\right],\left[\begin{array}{ccc}
1 & \mid & -2 \\
-- & -- & -- \\
-2 & \mid & 5
\end{array}\right]\right]$$


De esta manera y por el primer argumento mencionado, se concluye que:

$$\mathbf{x}_{1} \perp \mathbf{x}_{2}, \text { yа que: } \Sigma_{12}=\Sigma_{21} \neq 0$$
 AL ser provenientes de una particion de un vector normal.
 
 **b**
 
 $$\text { Se tiene que } \underline{X}^{(2)}=X_{2}, y \underline{X}^{(3)}=X_{3} \text {, asi que: }$$
 
 De esta manera se tiene que:
 
 $$\underline{\mathbf{X}}=\left[\begin{array}{c}
\underline{X}^{(2)} \\
\ldots \\
\underline{X}^{(3)}
\end{array}\right] \sim N_{2}\left[\left[\begin{array}{c}
1 \\
\cdots \\
4
\end{array}\right],\left[\begin{array}{ccc}
5 & \mid & 0 \\
-- & -- & -- \\
0 & \mid & 2
\end{array}\right]\right]$$
 
 Ahora, basado en los mismos argumentos ya mencionados, se concluye que los vectores son independientes pues $\mathbf{x}_{3} \perp \mathbf{x}_{2}, \text { sii } \Sigma_{12}=\Sigma_{21}=0$
 
 **c**
 
 $$\text { Se tiene que } \underline{X}^{(1)^{\prime}}=\left[X_{1}, X_{2}\right], y \underline{X}^{(2)}=X_{3} \text {, asi que: }$$
 Ahora, la particion con su respectiva distribucion es:
 
 $$\underline{\mathbf{X}}=\left[\begin{array}{c}
\underline{X}^{(1)} \\
\ldots \\
\underline{X}^{(2)}
\end{array}\right] \sim N_{3}\left[\left[\begin{array}{c}
-3 \\
1 \\
\ldots \\
4
\end{array}\right],\left[\begin{array}{cccc}
1 & -2 & \mid & 0 \\
-2 & 5 & \mid & 0 \\
-- & -- & -- & -- \\
0 & 0 & \mid & 2
\end{array}\right]\right]$$

Y nuevamente, como:

$$\Sigma_{12}=\Sigma_{21}=\operatorname{Cov}\left(\underline{X}^{(1)}, \underline{X}^{(2)}\right)=\left[\begin{array}{l}
0 \\
0
\end{array}\right]$$

Entonces se concluye que los vectores son independientes. 

**D**

$\left[\frac{X_{1}+X_{2}}{2}\right]$ y $X_{3}$ entonces:

$$
\begin{aligned}
&\underline{\mathbf{z}}_{1}: \frac{\mathbf{x}_{1}}{2}+\frac{\mathbf{x}_{2}}{2}+0 \mathbf{x}_{3} \\
&\underline{\mathbf{z}}_{2}: 0 \mathbf{x}_{1}+0 \mathbf{x}_{2}+\mathbf{x}_{3}
\end{aligned}
$$


Y Z está dado matricialmente como:

$$
\underline{\mathbf{Z}}=A \underline{X}=\left[\begin{array}{lll}
\frac{1}{2} & \frac{1}{2} & 0 \\
0 & 0 & 1
\end{array}\right]\left[\begin{array}{l}
x_{1} \\
x_{2} \\
x_{3}
\end{array}\right]
$$

Ahora, por propiedades de la normal multivariante vistas en clase;  la varianza de Z es tal que $A \Sigma_{x} A^{T}$

En este caso:

$$
A \Sigma_{x} A^{T}=\left[\begin{array}{ccc}
\frac{1}{2} & \frac{1}{2} & 0 \\
0 & 0 & 1
\end{array}\right]\left[\begin{array}{ccc}
1 & -2 & 0 \\
-2 & 5 & 0 \\
0 & 0 & 2
\end{array}\right]\left[\begin{array}{cc}
\frac{1}{2} & 0 \\
\frac{1}{2} & 0 \\
0 & 1
\end{array}\right]
$$
Ahora, al realizar las respectvas operaciones en matlab se tiene como resultado:

$$
\left[\begin{array}{cc}
1 / 2 & 0 \\
0 & 2
\end{array}\right]
$$


Y esta es la matriz de varianzas y covarianzas de z. Para entonces determinar si los vectores son independientes, se debe recordar que Z es un vector construido a partir de variables normales, entonces Z es normal y nuevamente, la independencia de los componentes de Z dependera de la matriz sigma de varianzas. La anterior calculada. En este caso:

$$
\text { - Como: } \sigma_{12}=\sigma_{21}=0, \quad z_{1} \perp z_{2}, \text { son independientes. }
$$

Por propiedades ya mencionadas. 

**e**

$X_{2} \quad y \quad X_{2}-\frac{5}{2} X_{1}-X_{3}$

Analogamente y citando los mismos atugmentos, se crea un vector Z con las dos combinaciones lineales de variables normales y por lo ya mencionado, basta calcular su matris de var-cov.

$$
A \Sigma_{x} A^{T}=\left[\begin{array}{ccc}
0 & 1 & 0 \\
\frac{-5}{2} & 1 & -1
\end{array}\right]\left[\begin{array}{ccc}
1 & -2 & 0 \\
-2 & 5 & 0 \\
0 & 0 & 2
\end{array}\right]\left[\begin{array}{cc}
0 & \frac{-5}{2} \\
1 & 1 \\
0 & -1
\end{array}\right]=\left[\begin{array}{cc}
5 & 10 \\
10 & 93 / 4
\end{array}\right]
$$

Dado estos resultados de la matriz de var-cov:

- Como: $\sigma_{12}=\sigma_{21}=10 \neq 0, \quad z_{1} \neq z_{2}$, por lo tanto no son independientes.:

# Ejercicio 2.

Se requiere hallar la distribucion condicional pedida. 

**a**

$X_{1} \mid X_{2}=x_{2}$


- Del ejercicio $4.2$ se tiene que $\mu_{1}=0, \mu_{2}=2, \sigma_{11}=2 \sigma_{22}=1$ y además: $\rho_{12}=0.5$


- Para hallar $\sigma_{12}$ se tiene que $\rho_{12}=\frac{\sigma_{12}}{\sqrt{\sigma_{11} \sigma_{22}}}$ de donde se despeja:

$$
\sigma_{12}=\frac{1}{2} \sqrt{2 * 1}=\frac{1}{\sqrt{2}} \Sigma=\left[\begin{array}{cc}
2 & 1 / \sqrt{2} \\
1 / \sqrt{2} & 1
\end{array}\right]
$$
Donde: $$ \frac{1}{\sqrt{2}}= \frac{\sqrt{2}}{2}= \frac{2}{2*\sqrt{2}}$$

Ahora, estos datos eran necesarios para calcular la distribucion condicional pedida pues:

$$
X_{1} \mid X_{2}=x_{2} \sim N_{1}\left(\mu_{1}+\frac{\sigma_{12}}{\sigma_{22}}\left(x_{2}-\mu_{2}\right), \sigma_{11}-\frac{\sigma_{12}}{\sigma_{22}} \sigma_{21}\right)
$$

Ahora, al reemplzar todos los valores, se tiene que:

$$
X_{1} \mid X_{2}=x_{2} \sim N_{1}\left(0+\frac{1 / \sqrt{2}}{1}\left(x_{2}-2\right), 2-\frac{1 / \sqrt{2}}{1/2} \frac{1}{\sqrt{2}}\right)=\left(\frac{1}{\sqrt{2}}\left(x_{2}-2\right), \frac{3}{2}\right)
$$

**b**
$X_{2} \mid X_{1}, X_{3}$

Del ejercicio anterioir se tiene que:

$$
\underline{X}=\left[\begin{array}{l}
X_{1} \\
X_{2} \\
X_{3}
\end{array}\right] \sim N_{3}(\mu, \Sigma) \operatorname{con} \underline{\mu}^{T}=[-3,1,4] y \Sigma=\left[\begin{array}{ccc}
1 & -2 & 0 \\
-2 & 5 & 0 \\
0 & 0 & 2
\end{array}\right]
$$

- Donde se particiona $\underline{X}$ de la siguiente manera:

$X^{(1)}=\left[X_{2}\right] \operatorname{con} \underline{\mu}^{ %>% (1)}=[1] y X^{(2)^{T}}=\left[X_{1}, X_{3}\right] \operatorname{con} \underline{\mu}^{(2)^{T}}=[-3,4]$


De esta manera, la matriz de var-cov particionada es:

$$
\underline{X}=\left[\begin{array}{c}
X_{2} \\
\cdots \\
X_{1} \\
x_{3}
\end{array}\right] \quad y \Sigma=\left[\begin{array}{cccc}
5 & \uparrow & -2 & 0 \\
- & - & - & - \\
-2 & \mid & 1 & 0 \\
0 & \mid & 0 & 2
\end{array}\right]
$$

Esta expresion es la matriz de var-cov se calcula la condicional.

$$
\mu=E\left[X^{(1)} \mid X^{(2)}\right]=\mu^{(1)}+\Sigma_{12} \Sigma_{22}^{-1}\left(\underline{\mathbf{x}}^{(2)}-\underline{\mu}^{(2)}\right)
$$

$$
E\left[X^{(1)} \mid X^{(2)}\right]=1+\left[\left[\begin{array}{ll}
-2 & 0
\end{array}\right]\left[\begin{array}{cc}
1 & 0 \\
0 & 1 / 2
\end{array}\right]\left(\left[\begin{array}{l}
X_{1} \\
X_{3}
\end{array}\right]-\left[\begin{array}{c}
-3 \\
4
\end{array}\right]\right)\right]
$$

Despues de realizar todas las operaciones pertinentes se llega a:

$$
-2 X_{1}-5
$$

Respecto a la varianza:

$$
\operatorname{Var}\left[X^{(1)} \mid X^{(2)}\right]=\sigma_{11}-\Sigma_{12} \Sigma_{22}^{-1} \Sigma_{21}
$$

$$
5-\left[\left[\begin{array}{ll}
-2 & 0
\end{array}\right]\left[\begin{array}{cc}
1 & 0 \\
0 & 1 / 2
\end{array}\right]\left[\begin{array}{c}
-2 \\
0
\end{array}\right]\right]=5-[4]=1
$$


Finalmente se concluye que:

$$
X_{2} \mid X_{1}, X_{3} \sim N_{1}\left(-2 X_{1}-5,1\right)
$$


**c**

Se tiene que $X_{3} \mid X_{1}, X_{2}$

Y dicha particion corresponde a:

$$
\underline{X}=\left[\begin{array}{l}
X_{1} \\
X_{2} \\
X_{3}
\end{array}\right] \sim N_{3}(\mu, \Sigma) \operatorname{con} \underline{\mu}^{T}=[2,-3,1] y \Sigma=\left[\begin{array}{lll}
1 & 1 & 1 \\
1 & 3 & 2 \\
1 & 2 & 2
\end{array}\right]
$$

$$
X^{(1)}=\left[X_{3}\right] \operatorname{con} \underline{\mu}^{(1)}=[1] y X^{(2)^{T}}=\left[X_{1}, X_{2}\right] \operatorname{con} \underline{\mu}^{(2)^{T}}=[2,-3]
$$

Ahora, la matriz de varianzas y covarianzas asociada a dicha particion es:

$$
\underline{X}=\left[\begin{array}{c}
X_{3} \\
\ldots \\
X_{1} \\
x_{2}
\end{array}\right] \text { y } \Sigma=\left[\begin{array}{cccc}
2 & \mid & 1 & 2 \\
- & - & - & - \\
1 & \mid & 1 & 1 \\
2 & \mid & 1 & 3
\end{array}\right]
$$


Todos estos datos son necesarios para seguir la formula de la distribucion condicional:

$$
\mu=E\left[X^{(1)} \mid X^{(2)}\right]=\mu^{(1)}+\Sigma_{12} \Sigma_{22}^{-1}\left(\underline{\mathbf{x}}^{(2)}-\underline{\mu}^{(2)}\right)
$$

$$
E\left[X^{(1)} \mid X^{(2)}\right]=1+\left[\left[\begin{array}{ll}
1 & 2
\end{array}\right]\left[\begin{array}{cc}
3 / 2 & -1 / 2 \\
-1 / 2 & 1 / 2
\end{array}\right]\left(\left[\begin{array}{l}
X_{1} \\
X_{2}
\end{array}\right]-\left[\begin{array}{l}
\space 2 \\
-3
\end{array}\right]\right)\right]
$$

Y al simplificar la expresion se obtiene que:

$$
X_{1} / 2+X_{2} / 2+3 / 2
$$

Ahora, para el calculo de la varianza para la condicional:

$$
\operatorname{Var}\left[X^{(1)} \mid X^{(2)}\right]=\sigma_{11}-\Sigma_{12} \Sigma_{22}^{-1} \Sigma_{21}
$$

Y reemplazando los valores se tiene que:

$$
\operatorname{Var}\left[X^{(1)} \mid X^{(2)}\right]=2-\left[\left[\begin{array}{ll}
1 & 2
\end{array}\right]\left[\begin{array}{cc}
3 / 2 & -1 / 2 \\
-1 / 2 & 1 / 2
\end{array}\right]\left[\begin{array}{l}
1 \\
2
\end{array}\right]\right]
$$

Al simplificar la anterior expresion se tiene que: $(2-[1 / 2+1]= 1/2$

Finalmente se tiene que:

$$
X_{3} \mid X_{1}, X_{2} \sim N_{1}\left(\frac{1}{2}\left(X_{1}+X_{2}+3\right), \frac{1}{2}\right)
$$

#Ejercicio 3

Sea $\mathrm{X}$ distribuida como $N_{3}(\mu, \Sigma)$, donde $\underline{\mu}^{T}=[1,-1,2] \space{y}:$

$$
\Sigma=\left[\begin{array}{ccc}
4 & 0 & -1 \\
0 & 5 & 0 \\
-1 & 0 & 2
\end{array}\right]
$$
Diga cuales de las siguientes variables son independitenes

**a**

X1 y X2.

- Se tiene que $\sigma_{12}=\sigma_{21}=0$, por lo tanto $X_{1} \space{y} X_{2}$ son independíentes, ya que ellas tienen una distribución normal bivariada con covarainza igual a 0 .

**b**

X1 y X3

- Se tiene que $\sigma_{13}=\sigma_{31}=-1 \neq 0$, por lo tanto $X_{1}$ y $X_{2}$ por lo tanto NO son independientes puesto que su covarianza es diferente de cero.

**c**

X2 y X3

- Se tiene que $\sigma_{23}=\sigma_{32}=0$, por lo tanto $X_{2} \mathrm{y} X_{3}$ son independientes,ya que ellas tienen una distribución normal bivariada con covarainza igual a 0 .

**d**

(X1,X3) y X2

$$
\text { Se tiene que } \underline{X}^{(1)^{\prime}}=\left[X_{1}, X_{3}\right], y \underline{X}^{(2)}=X_{2} \text {, asi que: }
$$

Y su respectiva particion es:

$$
\underline{\mathbf{X}}=\left[\begin{array}{c}
\underline{X}^{(1)} \\
\ldots \\
\underline{X}^{(2)}
\end{array}\right] \sim N_{3}\left[\left[\begin{array}{c}
1 \\
2 \\
\cdots \\
-1
\end{array}\right],\left[\begin{array}{cccc}
4 & -1 & \mid & 0 \\
-1 & 2 & \mid & 0 \\
-- & -- & -- & -- \\
0 & 0 & \mid & 5
\end{array}\right]\right]
$$
$$
\Sigma_{12}=\Sigma_{21}=\operatorname{Cov}\left(\underline{X}^{(1)}, \underline{X}^{(2)}\right)=\left[\begin{array}{l}
0 \\
0
\end{array}\right]
$$


$$
\begin{aligned}
&\text { - } X_{1}, X_{3} \mathrm{y} X_{2} \text { son independientes, ya que ellas tienen una distribución normal tri-variada con } \sigma_{12}=0 \\
&\text { y } \sigma_{32}=0 .
\end{aligned}
$$

Esto implica que:

$$
\operatorname{Cov}\left[\underline{x}^{(1)} ,x^{(2)}\right] = 0
$$

**e**

X1 y X1+3X2-2X3

Para esto, se plantea el siguiente esquema de vectores:

$$
\begin{aligned}
&\underline{Z}_{1}: \mathbf{x}_{1}+0 \mathbf{x}_{2}+0 \mathbf{x}_{3} \\
&\underline{\mathbf{Z}}_{2}: \mathbf{x}_{1}+3 \mathbf{x}_{2}-2 \mathbf{x}_{3}
\end{aligned}
$$
- En donde matricialmente $\underline{\mathbf{Z}}$ está dado por: $A \underline{X}$

$$
\underline{\mathbf{Z}}=A \underline{X}=\left[\begin{array}{ccc}
1 & 0 & 0 \\
1 & 3 & -2
\end{array}\right]\left[\begin{array}{l}
x_{1} \\
x_{2} \\
x_{3}
\end{array}\right]
$$


Y de esta manera, su matriz de var-cov es:

$$
A \Sigma_{x} A^{T}=\left[\begin{array}{ccc}
1 & 0 & 0 \\
1 & 3 & -2
\end{array}\right]\left[\begin{array}{ccc}
4 & 0 & -1 \\
0 & 5 & 0 \\
-1 & 0 & 2
\end{array}\right]\left[\begin{array}{cc}
1 & 1 \\
0 & 3 \\
0 & -2
\end{array}\right]=\left[\begin{array}{cc}
4 & 6 \\
6 & 61
\end{array}\right]
$$
Ahora, por propiedades vistas en clase, la combinacion lineal de vectores con variables aleatorias normales, se distribuye normal. 

Ahora, matricialmente, se tiene entonces esta matriz de varianza y covarianza proveniente de dicha combinacion lineal. Entonces, basta mirar la correlacion donde se ve que:

- Como: $\sigma_{12}=\sigma_{21}=6 \neq 0, z_{1} y z_{2}$ no son independientes.

# Ejercicio 4


a. $X_{1} \mid X_{3}=x_{3}$


$$
\begin{gathered}
X_{1} \mid X_{3}=x_{3} \sim N_{1}\left(\mu_{1}+\frac{\sigma_{13}}{\sigma_{33}}\left(x_{3}-\mu_{3}\right), \sigma_{11}-\frac{\sigma_{13}}{\sigma_{33}} \sigma_{31}\right) \\
X_{1} \mid X_{3}=x_{3} \sim N_{1}\left(1+\frac{-1}{2}\left(x_{3}-2\right), 4-\frac{-1}{2}(-1)\right)=N_{1}\left(1+0.5\left(x_{3}-2\right), 3.5\right)
\end{gathered}
$$

b. $X_{1} \mid x_{2}, x_{3}$


$$
X^{(1)}=\left[X_{1}\right] \operatorname{con} \underline{\mu}^{(1)}=[1] y X^{(2)^{T}}=\left[X_{2}, X_{3}\right] \operatorname{con} \underline{\mu}^{(2)^{T}}=[-1,2]
$$
Donde se tiene que:

$$
\underline{X}=\left[\begin{array}{c}
X_{1} \\
\cdots \\
X_{2} \\
x_{3}
\end{array}\right] y \Sigma=\left[\begin{array}{cccc}
4 & \mid & 0 & -1 \\
- & - & - & - \\
-0 & \mid & 5 & 0 \\
-1 & \mid & 0 & 2
\end{array}\right]
$$


Y esta expresion es necesaria para hallar la varianza condicional (formula usada anteriormente)

$$
E\left[X^{(1)} \mid X^{(2)}\right]=1+\left[[0-1]\left[\begin{array}{cc}
1 / 5 & 0 \\
0 & 1 / 2
\end{array}\right]\left(\left[\begin{array}{c}
X_{2} \\
X_{3}
\end{array}\right]-\left[\begin{array}{c}
-1 \\
2
\end{array}\right]\right)\right]=1+\frac{1}{2}(x 3-2)
$$
Y ka varianza es:

$$
\operatorname{Var}\left[X^{(1)} \mid X^{(2)}\right]=4-\left[\left[\begin{array}{ll}
-1 & 2
\end{array}\right]\left[\begin{array}{cc}
1 / 5 & 0 \\
0 & 1 / 2
\end{array}\right]\left[\begin{array}{c}
-1 \\
2
\end{array}\right]\right]=4-\left[\frac{1}{2}\right]=\frac{3}{2}
$$

Finalmente, se concluye que:

$$
X_{2} \mid X_{1}, X_{3} \sim N_{1}\left(-0.5 X_{3}+2,3.5\right)
$$

#Ejercicio 5

a. Encontrar la distribución marginal para cada uno de los vectores

$$
V_{1}: \frac{1}{4} \mathbf{x}_{1}-\frac{1}{4} \mathbf{x}_{2}+\frac{1}{4} \mathbf{x}_{3}-\frac{1}{4} \mathbf{x}_{4}
$$
$$
V_{2}: \frac{1}{4} \mathbf{x}_{1}+\frac{1}{4} \mathbf{x}_{2}-\frac{1}{4} \mathbf{x}_{3}-\frac{1}{4} \mathbf{x}_{4}
$$

Se tienen a combinaciones lineales de vectores aleabrior, por lo tanto:

Para $v_{1}=\frac{1}{4} x_{2}-\frac{1}{4} x_{2}+\frac{1}{4} x_{3}-\frac{1}{4} x_{4}$

Se tiene que: $C_{1}=c_{3}=\frac{1}{4}$ y $c_{2}=c_{3}=-\frac{1}{4} y$ $\mu_{j}=\mu$, para $j=1 \ldots 4$.

A demás, se tieneque $\sum_{j=1}^{4} c_{j} \mu_{j}=\frac{1}{4} \mu-\frac{1}{4} \mu_{}+\frac{1}{4} \mu-\frac{1}{4} \mu=0$

Para la varianza:

$\sum_{j=4}^{4}\left(c_{j}\right)^{2} \Sigma=\left(\frac{1}{16}+\frac{1}{16}+\frac{1}{16}+\frac{1}{16}\right) \sum=\frac{1}{4} \sum$

Finalmente:
$V_{1} \sim N\left(0, \frac{1}{4} \Sigma\right)$

Analogamente, para el segundo vector:

$V_{2}=\frac{1}{4} x_{1}+\frac{1}{4} x_{2}+\left(-\frac{1}{4}\right) x_{3}-\frac{1}{4} x 4$

Y procediendo de manera similar:

$V_2 \sim N(0, \frac{1}{4}\Sigma)$

Y estas son las distribuciones marginales de V1 y V2.

**b**
Encontrar la conjunta:

covarianza:

$$\sum_{j=4}^{4}\left(c_{j}*b_{j}\right) \Sigma=(1/16-1/16-1/16+1/16)=0$$

Finalmente el vector resultante es un vector con media de vector nulo y varianza dada por:

$$\begin{equation}
\begin{bmatrix}
\frac{1}{4} \Sigma & 0 \\
0 & \frac{1}{4} \\
\end{bmatrix}
\end{equation}$$


