---
title: "punto5"
author: "Karen Andrea Amaya"
date: "6/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


5) Utilice las técnicas ridge y lasso para regularizar las bases de datos BASE_DATOS_1 y BASE_DATOS_2. Según estas técnicas, ¿cuáles variables aparentemente muestran no ser relevantes para explicar la variable aleatoria Y ?
```{r}
base2 <- read.table("../BASE_DATOS_2.txt", header = T)
```


```{r}
require(ISLR)
require(glmnet) 
base2<-na.omit(base2) 
x<-model.matrix(Y~.,base2)[,-1] 
y<-base2$Y
gridz<-10^seq(-2,10, length=100) 
ridge.mod<-glmnet(x,y,alpha=0, lambda=gridz)
dim(coef(ridge.mod))
```
```{r}
plot(ridge.mod, xvar="lambda", label=TRUE)
```
```{r}
cedula<-1233
set.seed(cedula)
train<-sample(1: nrow(x), nrow(x)/2)
test<- -train
y.test<-y[test] 
cv.out<-cv.glmnet(x[train,],y[train],alpha=0)
```

```{r}
plot(cv.out)
```
```{r}
 bestlam<-cv.out$lambda.min ;bestlam
```

```{r}
ridge.pred<-predict(ridge.mod, s=bestlam,newx=x[test,] )
mean((ridge.pred-y.test)^2)
```

```{r}
out<-glmnet (x,y,alpha=0) 
pre <- predict(out,type="coefficients",s=bestlam)[1:147,]
```

```{r}
sort(abs(pre), decreasing = T)[1:21]
```



#Lasso

```{r}
x<-model.matrix(Y~.,base2)[,-1] 
y<-base2$Y
gridz<-10^seq(-2,10, length=100) 
lasso.mod<-glmnet(x,y,alpha=1, lambda=gridz)
dim(coef(lasso.mod))
```


```{r}
plot(lasso.mod, xvar="lambda", label=TRUE)
```

```{r}
cedula<-1233
set.seed(cedula)
train<-sample(1: nrow(x), nrow(x)/2)
test<- -train
y.test<-y[test] 
cv.out<-cv.glmnet(x[train,],y[train],alpha=1)
```

```{r}
plot(cv.out)
```

```{r}
 bestlam<-cv.out$lambda.min ;bestlam
```


```{r}
lasso.pred<-predict(lasso.mod, s=bestlam,newx=x[test,]) 
mean((lasso.pred-y.test)^2)
```


```{r}
out<-glmnet (x,y,alpha=1) 
lasso.coef<-predict(out,type="coefficients",s=bestlam)[1:147,] 
lasso.coef
```

```{r}
lasso.coef[lasso.coef!=0]
```







