library(kableExtra) #tablas
library(ISLR)
library(tree)
library(randomForest)
n <- length(Carseats$Sales)
set.seed(1)
train<- sample (n,(n*0.7))
arbol = tree(Sales~.,Carseats, subset = train)
summary(arbol)
plot(arbol)
text(arbol,pretty=0)
yhat = predict(arbol ,newdata = Carseats[-train ,])
arbol.test = Carseats[-train ,"Sales"]
mean((yhat-arbol.test)^2)
cv.arbol =cv.tree(arbol)
plot(cv.arbol$size ,cv.arbol$dev,type="b")
prune.carseats<-prune.tree(arbol,best=8)
plot(prune.carseats)
text(prune.carseats) 
yphat=predict(prune.carseats,Carseats[-train,])
arbolp.test = Carseats[-train ,"Sales"]
mean((yphat-arbolp.test)^2)
set.seed(1)
arbolbag<-randomForest(Sales~.,data=Carseats,subset=train,mtry=10,importance=T)
ybhat<-predict(arbolbag,Carseats[-train,])
mean((ybhat-Carseats[-train,"Sales"])^2)
importance(arbolbag) %>% kbl() %>% kable_styling()
set.seed(1)
bosque<-randomForest(Sales~.,data=Carseats,subset=train,mtry=5,importance=T)
yhat.rf<-predict(bosque,Carseats[-train,])
mean((yhat.rf-Carseats[-train,"Sales"])^2)
importance(bosque) %>% kbl() %>% kable_styling()
MSE=c()
set.seed(1)
for(i in 3:10){
  bosqueit=randomForest(Sales~.,data=Carseats,subset=train,mtry=i,importance=T)
  yhat.rfi=predict(bosqueit,Carseats[-train,])
  MSE<-rbind(MSE,mean((yhat.rfi-Carseats[-train,"Sales"])^2))
}
plot(3:10,MSE,type="b")
