---
title: "pruebas"
author: "Jhonatan Smith Garcia"
date: "2023-03-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

b) Encuentre $p \in(0,1)$, el porcentaje en que se reduce la esperanza de vida de $x_1$ con respecto a la vida $\left(x_1^s\right)$, dado por $\stackrel{e}{x}_{x_1}(1-p)=\stackrel{e}{x}_{x_1^s}$


## Solucion

Claro, para el inciso b) se tiene que la esperanza de vida para $x_1$ con $\mu_{x_1+t}$ está dada por:

$$\stackrel{e}{x}_{x_1} = \int_0^{\infty} t {t p{x_1}},{tp{x_1+t}},dt$$

Y para la vida $x_1^s$ con $\mu_{x_1^s+t}=\theta \mu_{x_1+t}$, se tiene:

$$\stackrel{e}{x}_{x_1^s} = \int_0^{\infty} t {t p{x_1^s}},{tp{x_1^s+t}},dt$$

Se quiere encontrar el porcentaje $p$ en que se reduce la esperanza de vida de $x_1$ con respecto a la vida $x_1^s$, es decir, se busca $p$ tal que:

$$(1-p)\stackrel{e}{x}{x_1}=\stackrel{e}{x}{x_1^s}$$

Por lo tanto, se necesita calcular primero las esperanzas de vida $\stackrel{e}{x}{x_1}$ y $\stackrel{e}{x}{x_1^s}$.


para el inciso b) se tiene que la esperanza de vida para $x_1$ con $\mu_{x_1+t}$ está dada por:

$$\stackrel{e}{x}_{x_1} = \int_0^{\infty} t {t p{x_1}},{tp{x_1+t}},dt$$

Y para la vida $x_1^s$ con $\mu_{x_1^s+t}=\theta \mu_{x_1+t}$, se tiene:

$$\stackrel{e}{x}_{x_1^s} = \int_0^{\infty} t {t p{x_1^s}},{tp{x_1^s+t}},dt$$

Se quiere encontrar el porcentaje $p$ en que se reduce la esperanza de vida de $x_1$ con respecto a la vida $x_1^s$, es decir, se busca $p$ tal que:

$$(1-p)\stackrel{e}{x}{x_1}=\stackrel{e}{x}{x_1^s}$$
Tenemos que la esperanza de vida residual para $x_1$ está dada por

$$
\stackrel{e}{x}_{x_1}=\int_0^{\infty} t_t p_{x_1} d t
$$

Despejando $p$ se obtiene:

$$p = 1 - \frac{\stackrel{e}{x}{x_1^s}}{\stackrel{e}{x}{x_1}}$$

Por lo tanto, se necesita calcular primero las esperanzas de vida $\stackrel{e}{x}{x_1}$ y $\stackrel{e}{x}{x_1^s}$.

$$
\stackrel{e}{x_{x_1^s}}=\int_0^{\infty} t q_{x_1^s}(t) d t=\int_0^{20} t q_{x_1^s}(t) d t+\int_{20}^{\infty} t q_{x_1^s}(t) d t
$$


$$
\stackrel{e}{x_{x_1}}=\frac{\int_0^{20} e^{-0.0091052 \int_{30}^{30+t} \mu_u d u} d t+\int_{20}^{\infty} e^{-\int_{30}^{30+t} \mu_u d u} d t}{\int_0^{\infty} e^{-\int_{30}^{30+t} \mu_u d u} d t}=45.6396
$$

$$
\begin{aligned}
& \approx 40.893 \\
&
\end{aligned}
$$


$$
\begin{aligned}
& \stackrel{e}{x_{x_1^s}}=\frac{1}{\mu_{x_1^s}}-\frac{e^{-\mu_{x_1}^* 20}}{\mu_{x_1^s}} \\
& \approx 44.502 \\
&
\end{aligned}
$$

$$
\begin{aligned}
& \stackrel{e}{x}_{x_1}(1-p)=\stackrel{e}{x}_{x_1^s} \\
& (40.893)(1-p)=44.502 \\
& 1-p=\frac{44.502}{40.893} \\
& p \approx 0.089 \\
&
\end{aligned}
$$
